<?php

/**
 * @file
 * Implementation of FLVC IR customizations.
 */

/**
 * Implements hook_menu().
 */
function flvc_ir_custom_menu() {
  $items = array();

  $items['admin/islandora/tools/flvc_ir_custom'] = array(
    'title' => 'FLVC Institutional Repository Custom Settings',
    'description' => 'Settings for FLVC Institutional Repository.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flvc_ir_custom_admin_form'),
    'access arguments' => array(ISLANDORA_ENTITIES_ADMINISTER_PERMISSION),
    'file' => 'includes/admin.form.inc',
  );

  $items['flvc_ir_get_parent_organizations/%islandora_object/datastream/MODS'] = array (
    'page callback' => 'flvc_ir_custom_get_parent_organizations',
    'page arguments' => array(1, 'MODS'),
    'file' => 'includes/utilities.inc',
    'access callback' => TRUE,
  );

  $items['flvc_ir_get_parent_organizations/%islandora_object/datastream/MADS'] = array (
    'page callback' => 'flvc_ir_custom_get_parent_organizations',
    'page arguments' => array(1, 'MADS'),
    'file' => 'includes/utilities.inc',
    'access callback' => TRUE,
  );
  $items['flvc_ir_get_parent_organizations_from_scholar/%'] = array (
    'page callback' => 'flvc_ir_custom_get_parent_organizations_from_scholar',
    'page arguments' => array(1),
    'file' => 'includes/utilities.inc',
    'access callback' => TRUE,
  );
  $items['flvc_ir_get_parent_organizations_from_org/%'] = array (
    'page callback' => 'flvc_ir_custom_get_parent_organizations_from_org',
    'page arguments' => array(1),
    'file' => 'includes/utilities.inc',
    'access callback' => TRUE,
  );
/*
  $items['dept_tree'] = array (
    'page callback' => 'flvc_ir_custom_display_full_organization_tree',
    'page arguments' => array(),
    'file' => 'includes/utilities.inc',
    'access callback' => TRUE,
  );
*/
  return $items;
}

/**
 * Implements hook_views_api().
 */
function flvc_ir_custom_views_api($module = NULL, $api = NULL) {
  return array(
    "api" => '3.0',
    'path' => drupal_get_path('module', 'flvc_ir_custom') . '/views',
  );
}

/**
 * Implements hook_block_info().
 */
function flvc_ir_custom_block_info() {
  return array(
    'flvc_ir_custom_organization_tree' => array(
      'info' => t('FLVC IR Organization Tree View'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function flvc_ir_custom_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'flvc_ir_custom_organization_tree':
      module_load_include('inc', 'flvc_ir_custom', 'includes/utilities');
      if (strpos(current_path(), 'islandora/object') === 0) {
        $object = menu_get_object('islandora_object', 2);
      }
      else {
        module_load_include('inc', 'islandora', 'includes/utilities');
        $root_pid = variable_get('flvc_ir_custom_root_organization_pid', '');
        $object = islandora_object_load($root_pid);
      }
        if ($object) {
          if (!in_array('islandora:organizationCModel', $object->models)) {
            break;
          }
          $block['subject'] = t('FLVC IR Organization Tree View');
          $block['content'] = flvc_ir_custom_get_solr_tree_view($object, 'MADS_parent_institution_ms', 'MADS_department_ms');
          break;
        }
      //}
    case 'flvc_ir_custom_collection_tree':
      module_load_include('inc', 'flvc_ir_custom', 'includes/utilities');
      if (strpos(current_path(), 'islandora/object') === 0) {
        $object = menu_get_object('islandora_object', 2);
        if ($object) {
          if (!in_array('islandora:collectionCModel', $object->models)) {
            break;
          }
          $block['subject'] = t('FLVC IR Collection Tree View');
          $block['content'] = flvc_ir_custom_get_solr_tree_view($object, 'RELS_EXT_isMemberOfCollection_uri_ms', 'fgs_label_s');
          break;
        }
      }
  }
  return $block;
}

/**
 * Implements hook_preprocess().
 *
 * We want to add the mads identifier[@type=u1] and affilation/organization values to the variables array when viewing a personCModel object.
 */
function flvc_ir_custom_preprocess_islandora_person(array &$variables) {
  drupal_add_css(drupal_get_path('theme', 'islandoratheme') . '/css/person.css', array('group' => CSS_THEME, 'type' => 'file'));

  $object = empty($variables['object']) ? NULL : $variables['object'];
  $u2 = $u1 = '';
  if (empty($object)) {
    return;
  }
  module_load_include('inc', 'flvc_ir_custom', 'includes/utilities');
  try {
    $u1 = flvc_ir_custom_get_u1($object, 'MADS');
    $u2 = flvc_ir_custom_get_u2($object);
  }
  catch (Exception $e) {
    watchdog_exception('FLVC IR Customizations', $e, 'Error retrieving u identifier from MADS datastream.', array(), WATCHDOG_ERROR);
  }
  $variables['u1'] = $u1;
  $variables['u2'] = $u2;
}

/**
 * Implements hook_preprocess().
 */
function flvc_ir_custom_preprocess_islandora_dept(array &$variables) {
  module_load_include('inc', 'flvc_ir_custom', 'includes/utilities');
  drupal_add_css(drupal_get_path('theme', 'islandoratheme') . '/css/organization.css', array('group' => CSS_THEME, 'type' => 'file'));
  $object = empty($variables['object']) ? NULL : $variables['object'];
  $parent_org = '';
  $parent_org = flvc_ir_custom_get_parent_organization($object);
  if (!empty($parent_org)) {
    $variables['parent_organization'] = $parent_org;
  }

  $tree_block = flvc_ir_custom_block_view('flvc_ir_custom_organization_tree');
  $variables['organization_tree'] = drupal_render($tree_block['content']);
}

/**
 * Implements hook_preprocess_theme().
 *
 * Checks the path, if it's an Entity Organization or Person TN DS then it uses JS to watermark
 * the resulting image.
 */
/*
function flvc_ir_custom_preprocess_image(&$variables) {

  $image_path = parse_url($variables['path'], PHP_URL_PATH);
  $image_path_parts = explode('/', $image_path);
  $size_of_image_path = count($image_path_parts);

  if (strpos($image_path, 'folder.png') > 0) {
  }

  if ($image_path_parts[$size_of_image_path - 1] == 'view' &&
      $image_path_parts[$size_of_image_path - 2] == 'TN' &&
      $image_path_parts[$size_of_image_path - 3] == 'datastream') {

    $pid = urldecode($image_path_parts[$size_of_image_path - 4]);
    $object = islandora_object_load($pid);

    if (in_array('islandora:organizationCModel', $object->models)) {
      drupal_add_js(drupal_get_path('module', 'flvc_ir_custom')
        . '/js/entity_overlay.js');
      if (isset($variables['#attributes']['class'])) {
        $variables['attributes']['class'] = $variables['#attributes']['class']
          . 'flvc_ir_custom_organization_tn';
      }
      else {
        $variables['attributes']['class'] = 'flvc_ir_custom_organization_tn';
      }
    }

    if (in_array('islandora:personCModel', $object->models)) {
      drupal_add_js(drupal_get_path('module', 'flvc_ir_custom')
        . '/js/entity_overlay.js');
      if (isset($variables['#attributes']['class'])) {
        $variables['attributes']['class'] = $variables['#attributes']['class']
          . 'flvc_ir_custom_person_tn';
      }
      else {
        $variables['attributes']['class'] = 'flvc_ir_custom_person_tn';
      }
    }

  }
}
*/
